const ActionTypes = {
    UPDATE_USER: "UPDATE_USER",
    UPDATE_USER_RESPONSE: "UPDATE_USER_RESPONSE",
    GET_USERS: "GET_USERS",
    GET_USERS_RESPONSE: "GET_USER_RESPONSE",
    ADD_USER: "ADD_USER",
    ADD_USER_RESPONSE: "ADD_USER_RESPONSE",
    DEL_USER: "DEL_USER",
    DEL_USER_RESPONSE: "DEL_USER_RESPONSE",
    // product
    UPDATE_PRODUCT: "UPDATE_PRODUCT",
    UPDATE_PRODUCT_RESPONSE: "UPDATE_PRODUCT_RESPONSE",
    GET_PRODUCTS: "GET_PRODUCTS",
    GET_PRODUCTS_RESPONSE: "GET_PRODUCTS_RESPONSE",
    ADD_PRODUCT: "ADD_PRODUCT",
    ADD_PRODUCT_RESPONSE: "ADD_PRODUCT_RESPONSE",
    DEL_PRODUCT: "DEL_PRODUCT",
    DEL_PRODUCT_RESPONSE: "DEL_PRODUCT_RESPONSE",
    // product category
    UPDATE_PRODUCT_CATEGORY: "UPDATE_PRODUCT_CATEGORY",
    UPDATE_PRODUCT_CATEGORY_RESPONSE: "UPDATE_PRODUCT_CATEGORY_RESPONSE",
    GET_PRODUCTS_CATEGORY: "GET_PRODUCTS_CATEGORY",
    GET_PRODUCTS_CATEGORY_RESPONSE: "GET_PRODUCTS_CATEGORY_RESPONSE",
    ADD_PRODUCT_CATEGORY: "ADD_PRODUCT_CATEGORY",
    ADD_PRODUCT_CATEGORY_RESPONSE: "ADD_PRODUCT_CATEGORY_RESPONSE",
    DEL_PRODUCT_CATEGORY: "DEL_PRODUCT_CATEGORY",
    DEL_PRODUCT_CATEGORY_RESPONSE: "DEL_PRODUCT_CATEGORY_RESPONSE",
    // login
    GET_LOGIN: "GET_LOGIN",
    GET_LOGIN_RESPONSE: "GET_LOGIN_RESPONSE", 
}

export default ActionTypes;